services:
  mariadb:
    build:
      context: "."
      dockerfile: "./docker/mysql/Dockerfile"
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=develop
      - MYSQL_PASSWORD=123123
      - MYSQL_DATABASE=memo
      - TZ=Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql
  webserver:
    build:
      context: "."
      dockerfile: "./docker/php-httpd/Dockerfile"
    container_name: webserver
    depends_on:
      - mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    #   start 一時操作用エントリポイント systemctlを実行可能にする
    # privileged: true
    # entrypoint: /sbin/init
    #   end   一時操作用エントリポイント systemctlを実行可能にする
    volumes:
      - ./php:/var/www/html
    restart: "unless-stopped"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: "serverName=localhost"
volumes:
  db_data:
    driver: local
